# Generated by Django 4.2.30 on 2026-07-13 21:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
