# Generated by Django 4.2.30 on 2026-06-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='is_available',
        ),
    ]
