# Generated by Django 4.2.30 on 2026-06-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_ingredient_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.tag'),
        ),
    ]
